

<!-- custom footer -->
<div class="custom-footer-wrapper">
<div class="custom-footer clearfix">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('custom_footer_block')->toHtml(); ?>
   <?php if(themeOptions('twittername')<>'') { ?>
    <div class="custom-footer-column">
  <div class="line">&nbsp;</div>
<h1><?php echo $this->__('Twitter') ?></h1>
<div class="twitter-posts">
   <script type="text/javascript">
jQuery(document).ready(function($){
 
 jQuery('#twitter_update_list').tweet({
 modpath: '<?php echo $this->getJsUrl('twitter/'); ?>',
 count: 3,
 username: '<?php echo themeOptions('twittername') ?>',
 template: '<div class="tweet-icon"></div><div class="text">{text}</div><div class="created">{time}</div>',
 loading_text: '<?php echo $this->__('Loading...') ?>'

});
 
});
</script>
   
  
    <ul id="twitter_update_list"></ul>
    <div class="follow-link"><a href="http://twitter.com/<?php echo themeOptions('twittername') ?>/"><?php echo $this->__('Follow us on Twitter') ?></a></div>
</div>
  </div>
     <?php } ?>
     

 <?php if(themeOptions('facebookgroupid')<>'') { ?>
<div class="custom-footer-column">
<div class="line">&nbsp;</div>
<h1><?php echo $this->__('Facebook') ?></h1>



<div class="facebookOuter">
 <div class="facebookInner">
  <div class="fb-like-box" data-href="http://www.facebook.com/pages/dx/<?php echo themeOptions('facebookgroupid') ?>" data-width="235" data-height="270" data-show-border="false" data-show-faces="true" data-colorscheme="light" data-stream="false" data-border-color="#fafafa" data-header="false"></div>       
 </div>
</div>
           
<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

    <!-- / Facebook -->
    <?php } ?>
    
  </div>



</div>
</div>
<!-- / custom footer -->


<!-- footer customer showcase -->
<div class="footer-showcase">
  <div class="additional-footer">
   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_customer_showcase')->toHtml(); ?>
  </div>
</div>
<!-- / footer customer showcase -->



<div class="footer-container">
    <div class="additional-footer">
    <!-- perfectum footer -->
     <div id="footer">
        <?php if(themeOptions('topbtn')): ?>                    
                        <div id="message"><a href="#top" id="top-link"></a></div> 
                    <?php endif; ?>
   <!-- columns -->
   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_menu')->toHtml(); ?>
   
  </div>
  </div>
    <!-- / perfectum footer -->
</div>




    <div class="footer-wrapper">
    <div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="footer-left">
        
	    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?><br>
            <?php echo $this->getCopyright() ?>&nbsp;&nbsp;
        
        </div>
        <div class="footer-right">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('payment_icons')->toHtml(); ?>
        </div>
    </div>
    </div>